### ISSUE TITLE
Do fizzbuzz

### ISSUE THREAD

**Issue by chilouis** [chilouis/gh-flow-practice#2]
## Tasks

- [x] print fizz, if i is multiple of 3
- [x] print buzz, if i is multiple of 5
- [x] print fizzbuzz if i is multiple of 15
- [x] Otherwise, print i itself

## Reference

- [Fizzbizz wikipedia](https://en.wikipedia.org/wiki/Fizz_buzz)
